### ISSUE TITLE
Upgrade to the latest and greatest Quartz

### ISSUE THREAD

**Issue by brianosaurus** [michaelklishin/quartzite#26]
the table_x.sql definitions from https://github.com/quartz-scheduler/quartz are further along than the version that quartzite requires. This makes it so that triggers don't fire but jobs can be inserted. 

I think the easy fix is to either update the required version of quartz or mention somewhere in the docs where to get the correct schema definitions.  

I found them here: https://github.com/quartz-scheduler/quartz/releases/tag/quartz-2.1.7

**Comment by michaelklishin** [comment]
Quartzite doesn't depend on the most recent version of Quartz because upgrading leads to test failures and I don't have the time to investigate.

**Comment by devn** [comment]
@michaelklishin We looked into the test failures when using quartz 2.2.3. All were resolved by tacking `(of-type AJob)` onto all of the job builders (except `test-job-builder-dsl-example3` which already had it) in `test/clojurewerkz/quartzite/test/jobs_test.clj`.

It wasn't immediately clear to me why `example3` had this call, where other test cases did not, but perhaps you or someone else reading this will know and be able to put together a quick patch to update to the latest quartz release.

Thanks,
Devin && Danielle

/cc @quephird

**Comment by MalloZup** [comment]
hi all any update on this or maybe help-needed? i would like to help

**Comment by MalloZup** [comment]
@devn @brianosaurus @michaelklishin feel free to have a look at PR linked! thx

**Comment by vemv** [comment]
I reckon that given https://github.com/michaelklishin/quartzite/commit/09b620155951d39a72ff2700e8b433d82ea900cc this issue can be closed?
