### ISSUE TITLE
Database connection with System/Component and Quartzite jobs 

### ISSUE THREAD

**Issue by joelkuiper** [michaelklishin/quartzite#27]
Hey, I'd like to have a job that does a daily update on the database. However, the database connection pool is defined as a component (in System). If I pass the connection as context to job it doesn't work since it gets coerced. What would be the idiomatic way of accessing database connections (or other variables) from within a job?

**Comment by michaelklishin** [comment]
Pass around a key that lets you fetch it from e.g. the system map.
