### ISSUE TITLE
Testing: How to execute a job without scheduling?

### ISSUE THREAD

**Issue by pate** [michaelklishin/quartzite#28]
How do I execute a job without scheduling it? Is there now way to run the `execute` method on a given Job definition so that I can test against my defjob definitions?

E.g.

```
(defjob AJob [ctx]
  (do-stuff-with ctx))

(. execute (AJob.) {:some-context 1})
```

From reading the tests, it seems like I have to go through the scheduler :/

**Comment by michaelklishin** [comment]
Using Java interop. I don't recall adding anything like that to Quartzite.
