### ISSUE TITLE
Unable to use DSL effectively

### ISSUE THREAD

**Issue by divs1210** [michaelklishin/quartzite#32]
I'm trying to create a trigger that runs once every day at a specified time.
The code for that is as follows:
```clojure
(t/build
  (t/with-identity "something")
  (t/with-schedule
    (qsdi/schedule
      (qsdi/starting-daily-at (qsdi/time-of-day hours mins 0)))))
```
But this doesn't do what I intended it to do, running the job once every minute instead.
I've switched to using cron-expressions for now, but would like to know what's the correct way to this.

TBH I find `quartzite`'s documentation to be severely lacking - there are numerous functions with similar names but no docstring telling what they're supposed to be doing.
What's the difference between [every-day](http://reference.clojurequartz.info/clojurewerkz.quartzite.schedule.daily-interval.html#var-every-day) and [on-every-day](http://reference.clojurequartz.info/clojurewerkz.quartzite.schedule.daily-interval.html#var-on-every-day), for example? They have similar names and the same arglist.

**Comment by michaelklishin** [comment]
DSL function names very closely follow Quartz's function names, same with schedules and other terminology. The docs are [open source](https://github.com/clojurewerkz/quartzite.docs), so is all of Quartzite: feel free to contribute improvements.

**Comment by michaelklishin** [comment]
I believe this [Quartzite trigger example](http://clojurequartz.info/articles/triggers.html#using_daily_interval_schedules) largely answers your question (it uses the interval of 2 minutes, not 1 day, but it should be reasonably easy to correct).
[Quartz 2.1.7 JavaDocs](http://www.quartz-scheduler.org/api/2.1.7/index.html) are fairly extensive and [Quartz tutorials](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/) provide at least a few hours of reading material, from the concepts to specific examples and schedule types.

Again, if you fine the docs lacking, you can either contribute or switch to a different scheduling library. I have dozens of other open source projects to maintain and can't promise to deliver doc updates in a reasonable time frame.

**Comment by divs1210** [comment]
Hey, michael! 
I was genuinely looking for an answer.
If I have to search for Quartz docs to effectively use Quartzite then that's a leaky abstraction.
Pulls me out of the REPL, makes me spill my coffee and pull my hair in fury.
Quil wraps over Processing but still provides links to the original docs from wrapping functions.
Maybe we could do something similar here?

**Comment by divs1210** [comment]
Thank you for the links and your work on the lib!

**Comment by michaelklishin** [comment]
Processing and Quartz have different domains and I cannot come up with obviously better names than what Quartz has, in particular in schedule builders. As I stated earlier, I'm all for guides and API reference improvements but it was never the goal of Quartzite to completely hide Quartz and Quartz's concepts from the user.

**Comment by michaelklishin** [comment]
There are existing Clojure libraries that either come up with their own concepts or at least try to wrap their underlying scheduling library as much as possible: `at-at` is one example. I'd certainly understand if someone decided to use them for that reason alone :)

Quartzite was a way for me to make using Quartz specifically more declarative and I'd still choose Quartz over any other generic scheduling JVM library today for its robustness, maturity and extensibility. Solving for the above also means trade-offs such as being tied to the concepts behind Quartz.
