### ISSUE TITLE
got "incorrect arity 1 for clojurewerkz.quartzite.jobs/of-type"

### ISSUE THREAD

**Issue by zsdz** [michaelklishin/quartzite#38]
I try to use the cron example as the get start page:
http://clojurequartz.info/articles/getting_started.html

the intellij give me the "incorrect arity 1 for clojurewerkz.quartzite.jobs/of-type" at line 

    (j/of-type NoOpJob)

I check the api doc:
http://reference.clojurequartz.info/clojurewerkz.quartzite.jobs.html#var-of-type

the function of type is have two arity:

    (of-type jb clazz)

is there something wrong?Thanks!

**Comment by michaelklishin** [comment]
The function is supposed to be used in a macro that threads through the first argument.
